"use client";
import { useEffect,useMemo,useState } from "react";
import { Eye,EyeOff,KeyRound,ShieldCheck } from "lucide-react";
import { PremiumButton } from "@/components/ui/PremiumButton";
import { useToast } from "@/components/ui/ToastProvider";
import { passwordStrength } from "../profile.schema";
import { cooldownMessage,profileService } from "../profile.service";

export function AccountSecurityCard(){const{toast}=useToast();const[current,setCurrent]=useState("");const[next,setNext]=useState("");const[confirmation,setConfirmation]=useState("");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[changes,setChanges]=useState<Array<{id:string;change_type:string;changed_at:string}>>([]);const strength=useMemo(()=>passwordStrength(next),[next]);useEffect(()=>{profileService.recentChanges().then(setChanges);},[]);
 async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);const result=await profileService.changePassword({currentPassword:current,newPassword:next,confirmPassword:confirmation});if(result.ok){setCurrent("");setNext("");setConfirmation("");setChanges(await profileService.recentChanges());toast("Your password was changed successfully.","success");}else toast(result.remainingSeconds?cooldownMessage(result.remainingSeconds,"password"):result.message,result.remainingSeconds?"warning":"error");setBusy(false);}
 const colors={weak:"bg-red-500",medium:"bg-amber-500",strong:"bg-emerald-500",excellent:"bg-wine"};
 return <section className="rounded-[1.5rem] border bg-paper p-6 shadow-card lg:col-span-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-wine/8 text-wine"><ShieldCheck className="h-5 w-5"/></span><div><p className="eyebrow">Account security</p><h2 className="font-serif text-2xl">Change your password securely</h2></div></div><div className="mt-6 grid gap-7 md:grid-cols-2"><form onSubmit={submit} className="space-y-4">{[["Current password",current,setCurrent],["New password",next,setNext],["Confirm new password",confirmation,setConfirmation]] .map(([label,value,setValue])=><label key={label as string} className="block text-sm font-semibold">{label as string}<span className="relative mt-2 block"><input required type={show?"text":"password"} value={value as string} onChange={event=>(setValue as (value:string)=>void)(event.target.value)} className="focus-ring h-12 w-full rounded-xl border bg-cream px-4 pr-12"/><button type="button" onClick={()=>setShow(value=>!value)} aria-label={show?"Hide passwords":"Show passwords"} className="absolute right-1 top-1 grid h-10 w-10 place-items-center rounded-full text-ink/45">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></span></label>)}{next&&<div><div className="flex items-center justify-between text-xs"><span>Password strength</span><strong className="capitalize">{strength.level}</strong></div><div className="mt-2 grid grid-cols-5 gap-1">{Array.from({length:5},(_,index)=><span key={index} className={`h-1.5 rounded-full ${index<strength.score?colors[strength.level]:"bg-ink/10"}`}/>)}</div><p className="mt-2 text-xs text-ink/45">Use 8+ characters with upper/lowercase letters, a number and a symbol.</p></div>}<PremiumButton type="submit" loading={busy} disabled={!current||!next||!confirmation}>Change password</PremiumButton><p className="text-[11px] leading-5 text-ink/40">Your current password is verified with Supabase Auth. Passwords are never stored in the Ourside database.</p></form><div><h3 className="flex items-center gap-2 text-sm font-bold"><KeyRound className="h-4 w-4 text-wine"/>Recent account changes</h3><div className="mt-3 space-y-2">{changes.length?changes.map(change=><div key={change.id} className="rounded-xl bg-cream p-3"><p className="text-xs font-bold capitalize">{change.change_type.replaceAll("_"," ")}</p><time className="text-[11px] text-ink/40">{new Date(change.changed_at).toLocaleString()}</time></div>):<p className="rounded-xl bg-cream p-4 text-xs text-ink/45">No recent security changes.</p>}</div><div className="mt-5 rounded-xl border border-dashed p-4"><p className="text-sm font-bold">Two-factor authentication</p><p className="mt-1 text-xs text-ink/45">Coming soon. This control is intentionally unavailable until secure enrollment is ready.</p><button disabled className="mt-3 min-h-10 rounded-full bg-ink/5 px-4 text-xs font-bold text-ink/35">Coming soon</button></div></div></div></section>}
