/** Authoritative server subscription reader. Development mock cookies are ignored in production. */
import { cookies } from "next/headers"; import { createServerSupabaseClient } from "@/lib/supabase/server"; import { MOCK_BILLING_ENABLED } from "./billing.constants"; import { mockSubscription } from "./billing.mock"; import type { PlanSlug, Subscription, SubscriptionStatus } from "./billing.types";
export async function getCurrentSubscription():Promise<Subscription|null>{
  const client=await createServerSupabaseClient();if(!client)return null;const {data:{user}}=await client.auth.getUser();if(!user)return null;
  if(MOCK_BILLING_ENABLED){const value=(await cookies()).get("ourside_mock_subscription")?.value;if(value){const [plan,status]=value.split(":") as [PlanSlug,SubscriptionStatus];if(["plus","lifetime"].includes(plan))return mockSubscription({userId:user.id,planSlug:plan,status:status||"active",currentPeriodEnd:status==="expired"?new Date(Date.now()-86_400_000).toISOString():mockSubscription().currentPeriodEnd});}}
  const {data}=await client.from("subscriptions").select("id,user_id,couple_id,plan_id,provider,provider_customer_id,provider_subscription_id,status,current_period_start,current_period_end,cancel_at_period_end,created_at,updated_at,plans!inner(slug)").in("status",["trialing","active","past_due"]).order("updated_at",{ascending:false}).limit(1).maybeSingle();
  if(!data)return null;const relation=data.plans as unknown as {slug:PlanSlug}|{slug:PlanSlug}[];const planSlug=Array.isArray(relation)?relation[0]?.slug:relation.slug;
  return{id:data.id,userId:data.user_id,coupleId:data.couple_id,planId:data.plan_id,planSlug:planSlug||"free",provider:data.provider,providerCustomerId:data.provider_customer_id,providerSubscriptionId:data.provider_subscription_id,status:data.status,currentPeriodStart:data.current_period_start,currentPeriodEnd:data.current_period_end,cancelAtPeriodEnd:data.cancel_at_period_end,createdAt:data.created_at,updatedAt:data.updated_at} as Subscription;
}
