import type { DynamicPlan, PlanFeatures, PlanLimits } from "./plans.types";

export const DEFAULT_LIMITS: PlanLimits = { memories: 50, mediaItems: 50, videos: 0, storageMb: 500, letters: 3, futureLetters: 3, milestones: 20, bucketListItems: 20, albums: 3, coupleMembers: 2, maxUploadMb: 10 };
export const DEFAULT_FEATURES: PlanFeatures = { videoUpload: false, premiumThemes: false, exportData: false, prioritySupport: false, advancedNotifications: false, storeOriginalImages: false, voiceNotes: false, relationshipYearbook: false };
const unlimited: PlanLimits = { memories: null, mediaItems: null, videos: null, storageMb: null, letters: null, futureLetters: null, milestones: null, bucketListItems: null, albums: null, coupleMembers: 2, maxUploadMb: 25 };
const premium: PlanFeatures = Object.fromEntries(Object.keys(DEFAULT_FEATURES).map(key => [key, true])) as unknown as PlanFeatures;
const regional = { US:{currency:"USD",monthly:5.99,yearly:59.99,lifetime:179},TR:{currency:"TRY",monthly:199,yearly:1990,lifetime:5990},EU:{currency:"EUR",monthly:5.49,yearly:54.99,lifetime:169},GB:{currency:"GBP",monthly:4.99,yearly:49.99,lifetime:149},CA:{currency:"CAD",monthly:7.99,yearly:79.99,lifetime:239},AU:{currency:"AUD",monthly:8.99,yearly:89.99,lifetime:269} };

export const FALLBACK_PUBLIC_PLANS: DynamicPlan[] = [
  { id:"fallback-free",slug:"free",name:"Keepsake",description:"For couples beginning their private story.",currency:"USD",monthlyPrice:0,yearlyPrice:0,lifetimePrice:0,monthlyPriceLabel:"Free",yearlyPriceLabel:"Free",lifetimePriceLabel:"Free",isFree:true,isActive:true,isPublic:true,isFeatured:false,trialDays:0,badgeText:null,ctaText:"Start free",displayOrder:0,limits:DEFAULT_LIMITS,features:DEFAULT_FEATURES,marketingFeatures:["Up to 50 memories","3 future letters","500 MB private storage","Private couple space"],regionalPrices:{} },
  { id:"fallback-plus",slug:"plus",name:"Ourside Plus",description:"Room for every chapter, letter, and little thing.",currency:"USD",monthlyPrice:5.99,yearlyPrice:59.99,lifetimePrice:null,monthlyPriceLabel:null,yearlyPriceLabel:null,lifetimePriceLabel:null,isFree:false,isActive:true,isPublic:true,isFeatured:true,trialDays:0,badgeText:"Most loved",ctaText:"Choose Plus",displayOrder:1,limits:unlimited,features:premium,marketingFeatures:["Unlimited memories and albums","Original-quality photo storage","Future letters with voice notes","Full memory export"],regionalPrices:regional },
  { id:"fallback-lifetime",slug:"lifetime",name:"Ourside Forever",description:"A permanent archive designed for a lifetime together.",currency:"USD",monthlyPrice:null,yearlyPrice:null,lifetimePrice:179,monthlyPriceLabel:null,yearlyPriceLabel:null,lifetimePriceLabel:null,isFree:false,isActive:true,isPublic:true,isFeatured:false,trialDays:0,badgeText:null,ctaText:"Choose Lifetime",displayOrder:2,limits:unlimited,features:premium,marketingFeatures:["Everything in Plus","One-time purchase","Long-term private archive","Full memory export"],regionalPrices:regional },
];
