/** Platform-neutral profile rules live here; browser image preparation remains isolated in avatar.client.ts. */
import { createClient } from "@/lib/supabase/client";
import { displayNameSchema,passwordChangeSchema } from "./profile.schema";
import type { PreparedAvatar } from "./avatar.client";

type Failure={ok:false;message:string;remainingSeconds?:number};type Success={ok:true};type ChangeStatus={ok:true;allowed:boolean;remainingSeconds:number;lastChangedAt:string|null};
export type ProfileDetails={displayName:string;email:string;avatarPath:string|null;avatarUrl:string|null;avatarUpdatedAt:string|null;displayNameUpdatedAt:string|null};
function failure(error:{message:string}):Failure{const match=/COOLDOWN:(\d+)/.exec(error.message);return{ok:false,message:match?`Please wait before changing this again.`:error.message,remainingSeconds:match?Number(match[1]):undefined};}
export function cooldownMessage(seconds:number,kind:"photo"|"name"|"password"){const minutes=Math.max(1,Math.ceil(seconds/60));if(minutes>=60){const hours=Math.ceil(minutes/60);return`You can change your ${kind} again in ${hours} hour${hours===1?"":"s"}.`;}return`You changed your ${kind} recently. Try again in ${minutes} minute${minutes===1?"":"s"}.`;}

export const profileService={
 async get():Promise<{ok:true;data:ProfileDetails}|Failure>{const client=createClient();if(!client)return{ok:false,message:"Supabase is not configured."};const{data:user}=await client.auth.getUser();if(!user.user)return{ok:false,message:"Authentication required."};const{data,error}=await client.from("profiles").select("display_name,avatar_url,avatar_updated_at,display_name_updated_at").eq("id",user.user.id).single();if(error)return failure(error);let avatarUrl:string|null=null;if(data.avatar_url){const signed=await client.storage.from("profile-media").createSignedUrl(data.avatar_url,3600);avatarUrl=signed.data?.signedUrl||null;}return{ok:true,data:{displayName:data.display_name||user.user.email?.split("@")[0]||"You",email:user.user.email||"",avatarPath:data.avatar_url,avatarUrl,avatarUpdatedAt:data.avatar_updated_at,displayNameUpdatedAt:data.display_name_updated_at}};},
 async status(kind:"avatar_update"|"display_name_update"|"password_change"):Promise<ChangeStatus|Failure>{const client=createClient();if(!client)return{ok:false,message:"Supabase is not configured."};const{data,error}=await client.rpc("get_account_change_status",{change_kind:kind});if(error)return failure(error);const row=data?.[0];return{ok:true,allowed:Boolean(row?.allowed),remainingSeconds:Number(row?.remaining_seconds||0),lastChangedAt:row?.last_changed_at||null};},
 async recentChanges(){const client=createClient();if(!client)return[];const{data}=await client.from("account_change_logs").select("id,change_type,changed_at").order("changed_at",{ascending:false}).limit(5);return data||[];},
 async updateDisplayName(value:string):Promise<Success|Failure>{const parsed=displayNameSchema.safeParse(value);if(!parsed.success)return{ok:false,message:parsed.error.issues[0].message};const client=createClient();if(!client)return{ok:false,message:"Supabase is not configured."};const{error}=await client.rpc("update_my_display_name",{new_display_name:parsed.data});if(error)return failure(error);await client.auth.updateUser({data:{display_name:parsed.data}});void client.rpc("dispatch_profile_security_notification",{input_type:"display_name_updated"});return{ok:true};},
 async uploadAvatar(image:PreparedAvatar,onProgress?:(value:number)=>void):Promise<Success|Failure>{const client=createClient();if(!client)return{ok:false,message:"Supabase is not configured."};const status=await this.status("avatar_update");if(!status.ok)return status;if(!status.allowed)return{ok:false,message:cooldownMessage(status.remainingSeconds,"photo"),remainingSeconds:status.remainingSeconds};const{data:user}=await client.auth.getUser();if(!user.user)return{ok:false,message:"Authentication required."};const paths:string[]=[];for(let index=0;index<image.variants.length;index++){const variant=image.variants[index];const path=`users/${user.user.id}/avatar/avatar-${variant.name}.webp`;const{error}=await client.storage.from("profile-media").upload(path,variant.blob,{contentType:"image/webp",upsert:true,cacheControl:"3600"});if(error)return failure(error);paths.push(path);onProgress?.(Math.round(((index+1)/image.variants.length)*85));}const medium=paths.find(path=>path.includes("medium"))!;const{error}=await client.rpc("commit_my_avatar_update",{storage_path:medium});if(error)return failure(error);onProgress?.(100);void client.rpc("dispatch_profile_security_notification",{input_type:"profile_photo_updated"});return{ok:true};},
 async removeAvatar():Promise<Success|Failure>{const client=createClient();if(!client)return{ok:false,message:"Supabase is not configured."};const status=await this.status("avatar_update");if(!status.ok)return status;if(!status.allowed)return{ok:false,message:cooldownMessage(status.remainingSeconds,"photo"),remainingSeconds:status.remainingSeconds};const{data:user}=await client.auth.getUser();if(!user.user)return{ok:false,message:"Authentication required."};const{error}=await client.rpc("commit_my_avatar_update",{storage_path:null});if(error)return failure(error);await client.storage.from("profile-media").remove(["small","medium","large"].map(name=>`users/${user.user!.id}/avatar/avatar-${name}.webp`));return{ok:true};},
 async changePassword(input:{currentPassword:string;newPassword:string;confirmPassword:string}):Promise<Success|Failure>{const parsed=passwordChangeSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0].message};const client=createClient();if(!client)return{ok:false,message:"Supabase is not configured."};const status=await this.status("password_change");if(!status.ok)return status;if(!status.allowed)return{ok:false,message:cooldownMessage(status.remainingSeconds,"password"),remainingSeconds:status.remainingSeconds};const{data:user}=await client.auth.getUser();if(!user.user?.email)return{ok:false,message:"Authentication required."};const reauth=await client.auth.signInWithPassword({email:user.user.email,password:parsed.data.currentPassword});if(reauth.error)return{ok:false,message:"Current password is incorrect or your session must be refreshed."};const update=await client.auth.updateUser({password:parsed.data.newPassword});if(update.error)return{ok:false,message:"Your password could not be changed. Please try again securely."};const audit=await client.rpc("record_my_password_change");if(audit.error)return failure(audit.error);return{ok:true};}
};
