"use client";
import { use,useCallback,useEffect,useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft,Calendar,Heart,MapPin,Pencil,Trash2,X } from "lucide-react";
import { PremiumButton } from "@/components/ui/PremiumButton";
import { useToast } from "@/components/ui/ToastProvider";
import { useAppDialog } from "@/components/shared/dialogs/DialogProvider";
import { liveMemoryService } from "@/features/memories/memory.supabase";
import { subscribeToTable } from "@/lib/supabase/realtime";
import type { Memory } from "@/types/database";
import { AppLoader } from "@/components/shared/loading/AppLoader";

type Comment={id:string;body:string;author:string};
export default function MemoryDetail({params}:{params:Promise<{id:string}>}){const{id}=use(params);const router=useRouter();const{toast}=useToast();const{confirm:askConfirm}=useAppDialog();const[memory,setMemory]=useState<Memory|null>(null);const[comments,setComments]=useState<Comment[]>([]);const[loading,setLoading]=useState(true);const[editing,setEditing]=useState(false);const[title,setTitle]=useState("");const[note,setNote]=useState("");const[comment,setComment]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[item,thread]=await Promise.all([liveMemoryService.get(id),liveMemoryService.listComments(id)]);setMemory(item);setComments(thread);if(item){setTitle(item.title);setNote(item.note);}}catch(error){toast(error instanceof Error?error.message:"Memory could not be loaded.","error");}finally{setLoading(false);}},[id,toast]);
 useEffect(()=>{void load();const stopMemories=subscribeToTable("memories",()=>void load());const stopComments=subscribeToTable("memory_comments",()=>void load());return()=>{stopMemories();stopComments();};},[load]);
 async function favorite(){if(!memory||busy)return;const next=!memory.favorite;setMemory({...memory,favorite:next});try{await liveMemoryService.setFavorite(memory.id,next);toast(next?"Added to both partners’ favorites.":"Removed from favorites.","success");}catch(error){setMemory(memory);toast(error instanceof Error?error.message:"Favorite could not be updated.","error");}}
 async function save(event:React.FormEvent){event.preventDefault();if(!memory||busy)return;setBusy(true);try{await liveMemoryService.update(memory.id,{title,note});setMemory({...memory,title,note});setEditing(false);toast("Memory updated for both partners.","success");}catch(error){toast(error instanceof Error?error.message:"Memory could not be updated.","error");}finally{setBusy(false);}}
 async function remove(){if(!memory||busy)return;const accepted=await askConfirm({title:"Delete this memory?",description:"This removes the shared memory for both partners. This action cannot be undone.",confirmLabel:"Delete memory",cancelLabel:"Keep memory",tone:"destructive"});if(!accepted)return;setBusy(true);try{await liveMemoryService.remove(memory.id);toast("Memory deleted.","success");router.replace("/memories");}catch(error){setBusy(false);toast(error instanceof Error?error.message:"Memory could not be deleted.","error");}}
 async function addComment(event:React.FormEvent){event.preventDefault();if(!comment.trim()||busy)return;setBusy(true);try{await liveMemoryService.addComment(id,comment);setComment("");setComments(await liveMemoryService.listComments(id));toast("Private comment shared.","success");}catch(error){toast(error instanceof Error?error.message:"Comment could not be saved.","error");}finally{setBusy(false);}}
 if(loading)return <AppLoader label="Opening this memory…"/>;
 if(!memory)return <div className="mx-auto max-w-xl rounded-2xl border bg-paper p-10 text-center"><h1 className="font-serif text-4xl">Memory not found.</h1><PremiumButton href="/memories" className="mt-6">Back to timeline</PremiumButton></div>;
 return <div className="mx-auto max-w-6xl"><Link href="/memories" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-wine"><ArrowLeft className="h-4 w-4"/>Back to timeline</Link><article className="overflow-hidden rounded-[2rem] border bg-paper shadow-warm"><div className="grid lg:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-[52vh] bg-ink">{memory.imageUrl?<Image src={memory.imageUrl} alt={memory.title} fill sizes="(min-width:1024px) 60vw,100vw" className="object-cover" priority/>:<div className="paper-grid absolute inset-0 grid place-items-center p-12 font-serif text-4xl italic text-wine">“{memory.note}”</div>}</div><div className="flex flex-col p-6 sm:p-9"><div className="flex items-center justify-between"><p className="eyebrow">A page from our story</p><button type="button" aria-label="Favorite" aria-pressed={memory.favorite} onClick={()=>void favorite()} className="focus-ring grid h-11 w-11 place-items-center rounded-full border text-wine active:scale-95"><Heart className="h-5 w-5" fill={memory.favorite?"currentColor":"none"}/></button></div><h1 className="mt-5 font-serif text-4xl">{memory.title}</h1><div className="mt-5 flex flex-wrap gap-3 text-xs text-ink/55"><span className="flex items-center gap-1"><Calendar className="h-3.5 w-3.5"/>{new Date(memory.date).toLocaleDateString()}</span>{memory.location&&<span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{memory.location}</span>}</div><p className="mt-8 font-serif text-xl italic leading-9 text-ink/70">“{memory.note}”</p><p className="mt-3 text-xs text-ink/40">Added by {memory.author}</p><div className="mt-8 border-t pt-6"><p className="eyebrow">Between us</p>{comments.map(item=><div key={item.id} className="mt-3 rounded-2xl bg-cream p-4"><strong className="text-sm">{item.author}</strong><p className="mt-1 text-sm text-ink/60">{item.body}</p></div>)}<form onSubmit={addComment} className="mt-3 flex gap-2"><input value={comment} onChange={event=>setComment(event.target.value)} placeholder="Leave a private comment…" className="focus-ring h-11 min-w-0 flex-1 rounded-full border bg-cream px-4 text-sm"/><button type="submit" disabled={busy||!comment.trim()} className="rounded-full bg-wine px-4 text-xs font-bold text-white disabled:opacity-50">Send</button></form></div><div className="mt-8 flex gap-5 border-t pt-6 text-sm font-bold"><button type="button" onClick={()=>setEditing(true)} className="flex items-center gap-2"><Pencil className="h-4 w-4"/>Edit</button><button type="button" onClick={()=>void remove()} className="flex items-center gap-2 text-red-700"><Trash2 className="h-4 w-4"/>Delete</button></div></div></div></article>
 {editing&&<div className="fixed inset-0 z-[150] grid place-items-center bg-ink/45 p-5" role="dialog" aria-modal="true"><form onSubmit={save} className="w-full max-w-lg rounded-[1.5rem] bg-paper p-6 shadow-warm"><button type="button" aria-label="Close" onClick={()=>setEditing(false)} className="ml-auto grid h-10 w-10 place-items-center rounded-full"><X/></button><h2 className="font-serif text-3xl">Edit memory</h2><label className="mt-5 block text-sm font-bold">Title<input required value={title} onChange={event=>setTitle(event.target.value)} className="focus-ring mt-2 h-12 w-full rounded-xl border bg-cream px-4"/></label><label className="mt-4 block text-sm font-bold">Story<textarea value={note} onChange={event=>setNote(event.target.value)} className="focus-ring mt-2 min-h-28 w-full rounded-xl border bg-cream p-4"/></label><PremiumButton type="submit" disabled={busy} ariaBusy={busy} className="mt-5">{busy?"Saving…":"Save changes"}</PremiumButton></form></div>}</div>}
