"use client";
import { useEffect,useState } from "react";
import { BellRing,Mail,Smartphone } from "lucide-react";
import { notificationService } from "../notification.service";
import { NOTIFICATION_CATEGORIES } from "../notification.constants";
import type { NotificationChannel } from "../notification.types";
import { useToast } from "@/components/ui/ToastProvider";
import { useLocale } from "@/i18n/LocaleProvider";

const categoryLabels={
 partner_activity:{en:"Partner activity",tr:"Partner hareketleri",de:"Partneraktivität",es:"Actividad de pareja",fr:"Activité du partenaire"},
 memory_updates:{en:"Memory updates",tr:"Anı güncellemeleri",de:"Erinnerungsupdates",es:"Actualizaciones de recuerdos",fr:"Mises à jour des souvenirs"},
 letters_vault:{en:"Letters and vault",tr:"Mektuplar ve kasa",de:"Briefe und Tresor",es:"Cartas y bóveda",fr:"Lettres et coffre"},
 milestones:{en:"Milestone reminders",tr:"Dönüm noktası hatırlatmaları",de:"Meilenstein-Erinnerungen",es:"Recordatorios de hitos",fr:"Rappels de jalons"},
 daily_questions:{en:"Daily questions",tr:"Günlük sorular",de:"Tägliche Fragen",es:"Preguntas diarias",fr:"Questions quotidiennes"},
 product_billing:{en:"Product and billing",tr:"Ürün ve ödeme",de:"Produkt und Abrechnung",es:"Producto y facturación",fr:"Produit et facturation"}
} as const;
export function NotificationSettings(){const{locale,t}=useLocale();const tr=locale==="tr";const{toast}=useToast();const[values,setValues]=useState<Record<string,boolean>>({"in_app:*":true,"email:*":true,"push:*":false,"email:marketing":false});const[loading,setLoading]=useState(true);
 useEffect(()=>{notificationService.preferences().then(rows=>{setValues(current=>({...current,...Object.fromEntries(rows.map(row=>[`${row.channel}:${row.type}`,row.enabled]))}));}).catch(()=>toast(tr?"Bildirim tercihleri yüklenemedi.":"Notification preferences could not be loaded.","error")).finally(()=>setLoading(false));},[toast,tr]);
 async function toggle(channel:NotificationChannel,type:string,enabled:boolean){const key=`${channel}:${type}`;setValues(current=>({...current,[key]:enabled}));try{await notificationService.setPreference(channel,type,enabled);toast(tr?"Bildirim tercihi kaydedildi.":"Notification preference saved.","success");}catch(error){setValues(current=>({...current,[key]:!enabled}));toast(error instanceof Error?error.message:"Preference could not be saved.","error");}}
 async function toggleCategory(category:keyof typeof NOTIFICATION_CATEGORIES,enabled:boolean){setValues(current=>({...current,[`category:${category}`]:enabled}));try{await Promise.all(NOTIFICATION_CATEGORIES[category].flatMap(type=>[notificationService.setPreference("in_app",type,enabled),notificationService.setPreference("email",type,enabled)]));toast(tr?"Bildirim grubu güncellendi.":"Notification group updated.","success");}catch(error){toast(error instanceof Error?error.message:"Preferences could not be saved.","error");}}
 return <section className="rounded-[1.5rem] border bg-paper p-6 shadow-card lg:col-span-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-wine/8 text-wine"><BellRing className="h-5 w-5"/></span><div><h2 className="font-serif text-2xl">{t("notifications.preferences")}</h2><p className="text-xs text-ink/45">{t("notifications.preferencesText")}</p></div></div>{loading?<div className="mt-6 h-32 animate-pulse rounded-xl bg-wine/5"/>:<><div className="mt-6 grid gap-3 sm:grid-cols-3"><Channel icon={BellRing} label={t("notifications.inApp")} checked={values["in_app:*"]!==false} onChange={value=>void toggle("in_app","*",value)}/><Channel icon={Mail} label="Email" checked={values["email:*"]!==false} onChange={value=>void toggle("email","*",value)}/><Channel icon={Smartphone} label={t("notifications.pushSoon")} checked={false} disabled onChange={()=>{}}/></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{(Object.keys(NOTIFICATION_CATEGORIES) as Array<keyof typeof NOTIFICATION_CATEGORIES>).map(category=><Channel key={category} label={categoryLabels[category][locale]} checked={values[`category:${category}`]!==false} onChange={value=>void toggleCategory(category,value)}/>)}</div><div className="mt-4 border-t pt-4"><Channel label={tr?"Pazarlama e-postaları (varsayılan kapalı)":"Marketing emails (off by default)"} checked={Boolean(values["email:marketing"])} onChange={value=>void toggle("email","marketing",value)}/></div></>}</section>}
function Channel({icon:Icon,label,checked,onChange,disabled=false}:{icon?:typeof BellRing;label:string;checked:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <label className={`flex min-h-14 items-center gap-3 rounded-xl border bg-cream px-4 ${disabled?"cursor-not-allowed opacity-45":"cursor-pointer"}`}>{Icon&&<Icon className="h-4 w-4 text-wine"/>}<span className="flex-1 text-sm font-semibold">{label}</span><input type="checkbox" checked={checked} disabled={disabled} onChange={event=>onChange(event.target.checked)} className="h-5 w-5 accent-wine"/></label>}
